version: "3.9"
services:
  sonarqube:
    image: sonarqube:community
    container_name: "sonarqube"
    hostname: "sonarqube"
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      # The first default user/password is admin/admin
      SONAR_JDBC_USERNAME: ${SONAR_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_PASSWORD}
    volumes:
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - my-network
  db:
    image: postgres:13
    container_name: "postgres"
    hostname: "postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Exposing port to host
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - db:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - my-network
networks:
  my-network:
      name: my-network
      external: true
volumes:
  data:
  extensions:
  logs:
  db:
