version: "3.9"
services:
  sonarqube:
    image: sonarqube:community
    container_name: "sonarqube"
    hostname: "sonarqube"
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: ${SONAR_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_PASSWORD}
    volumes:
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:13
    container_name: "postgres"
    hostname: "postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Exposing port to host
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
volumes:
  data:
  extensions:
  logs:
  db:


# Need to increase vm.max_map count. Run as root / sudo:
# sudo sysctl -w vm.max_map_count=262144
