version: '3.9'

services:
  openldap:
    image: bitnami/openldap
    container_name: "openldap"
    hostname: "openldap"
    privileged: true
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      # Edited
      - LDAP_ORGANISATION=My Organization
      - LDAP_DOMAIN=example.com
      - LDAP_TLS=no
    volumes:
      - 'openldap_data:/bitnami/openldap/data'

volumes:
  openldap_data:
    driver: local
