version: '3.1'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: "oracle"
    hostname: "oracle"
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521
    volumes:
      - data:/opt/oracle/oradata
      - backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  data:
  backup:


# User: system
# Password: Oracle_123
# SID: XE  (Uppercase)

