version: "3.9"
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "9090:8181"
    environment:
      NIFI_WEB_HTTP_PORT: 8181
    volumes:
      - /home/votc/data/nifi/conf:/opt/nifi/nifi-current-conf
