version: "3.9"
services:
  nifi:
    user: root
    image: apache/nifi:latest
    container_name: "nifi"
    hostname: "nifi"
    ports:
      - "9090:8181"
      # - "8443:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8181
      # NIFI_WEB_HTTPS_PORT: 8443
      # SINGLE_USER_CREDENTIALS_USERNAME: admin
      # SINGLE_USER_CREDENTIALS_PASSWORD: admin
    volumes:
      - ~/data/nifi/nifi-current/db:/opt/nifi/nifi-current/db
      - ~/data/nifi/nifi-current/flowfile:/opt/nifi/nifi-current/flowfile
      - ~/data/nifi/nifi-current/state:/opt/nifi/nifi-current/state
      - ~/data/nifi/nifi-current/logs:/opt/nifi/nifi-current/logs
      - ./addresses.csv:/opt/nifi/nifi-current/content/addresses.csv
      - ./postgresql-42.5.1.jar:/opt/nifi/nifi-current/lib/postgresql-42.5.1.jar
    networks:
      - my-network
  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: "nifi-registry"
    hostname: "nifi-registry"
    ports:
      - "19090:18080"
    environment:
      NIFI_REGISTRY_WEB_HTTP_PORT: "18080"
    volumes:
      - ~/data/nifi-registry/database:/opt/nifi-registry/database
      - ~/data/nifi-registry/flow_storage:/opt/nifi-registry/flow_storage
    networks:
      - my-network
    depends_on:
      - nifi
networks:
  my-network:
      name: my-network

# docker network create my-network
# localhost == host.docker.internal
