version: "3.9"
services:
  nifi:
    user: root
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    ports:
      - "9090:8181"
    environment:
      NIFI_WEB_HTTP_PORT: 8181
    volumes:
      - ~/data/nifi/nifi-current/db:/opt/nifi/nifi-current/db
      - ~/data/nifi/nifi-current/flowfile:/opt/nifi/nifi-current/flowfile
      - ~/data/nifi/nifi-current/state:/opt/nifi/nifi-current/state
      - ~/data/nifi/nifi-current/logs:/opt/nifi/nifi-current/logs
      - ./addresses.csv:/opt/nifi/nifi-current/content/addresses.csv
      - ./postgresql-42.5.1.jar:/opt/nifi/nifi-current/lib/postgresql-42.5.1.jar
    networks:
      - my-network

networks:
  my-network:
      name: my-network

# docker network create my-network
