version: "3.9"
services:
  nifi:
    user: root
    image: apache/nifi:latest
    container_name: "nifi"
    hostname: "nifi"
    ports:
      - "9090:8181"
      # - "8443:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8181
      # NIFI_WEB_HTTPS_PORT: 8443
      # SINGLE_USER_CREDENTIALS_USERNAME: admin
      # SINGLE_USER_CREDENTIALS_PASSWORD: admin
    volumes:
      - database_repository:/opt/nifi/nifi-current/database_repository
      - flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - content_repository:/opt/nifi/nifi-current/content_repository
      - provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - state:/opt/nifi/nifi-current/state
      - logs:/opt/nifi/nifi-current/logs
      - conf:/opt/nifi/nifi-current/conf
      # For PostgreSQL use. You can remove it.
      - ./postgresql-42.5.1.jar:/opt/nifi/nifi-current/lib/postgresql-42.5.1.jar
      # For my personal ETL flow practice. You can remove it.
      - ./addresses.csv:/opt/nifi/nifi-current/content/addresses.csv
    networks:
      - my-network
networks:
  my-network:
      name: my-network

volumes:
  database_repository:
  flowfile_repository:
  content_repository:
  provenance_repository:
  state:
  logs:
  conf:
