services:
  redmine:
    image: redmine:latest
    container_name: "redmine"
    hostname: "redmine"
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DATABASE_HOST: mysql
      REDMINE_DATABASE_PORT_NUMBER: 3036
      REDMINE_DATABASE_NAME: ${DATABASE}
      REDMINE_DATABASE_PASSWORD: ${PASSWORD}
    links:
      - db
  db:
    image: mysql:latest
    container_name: "mysql"
    hostname: "mysql"
    # restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
