services:
  postgres:
    image: postgres
    container_name: "postgres"
    hostname: postgres
    # restart: always
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      #- ~/data/postgres:/var/lib/postgresql/data
    networks:
      - my-network
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my-network
  keycloak:
    image:  quay.io/keycloak/keycloak:latest
    container_name: keycloak
    hostname: keycloak
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${DATABASE}
      DB_USER: ${USERNAME}
      DB_SCHEMA: public
      DB_PASSWORD: ${PASSWORD}
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    command: start-dev
    networks:
      - my-network

networks:
  my-network:
      name: my-network
      external: true

volumes:
  db:
