scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']

#  - job_name: 'Spring Boot Application Input'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 2s
#    static_configs:
#      - targets: ['host.docker.internal:8080']
#        labels:
#          application: 'My Spring Boot Application'
