version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: "jenkins"
    hostname: "jenkins"
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

volumes:
  home:
