services:
  cassandra:
    image: cassandra:latest
    container_name: "cassandra"
    hostname: "cassandra"
    ports:
      - "9042:9042"
    volumes:
      - cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "cassandra"
volumes:
  cassandra:
