version: '3.9'
services:
  cassandra:
    image: cassandra:latest
    container_name: "cassandradb"
    ports:
      - "9042:9042"
    volumes:
      - ~/data/cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "cassandra"
